In [1]:
from torch.utils import data

import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
from torch.autograd import Variable
import numpy as np

import networkx as nx

In [2]:
G = nx.Graph()

In [3]:

nodes = []
node_map = {}
node_id = 0
with open('../Data/soc-sign-bitcoinalpha.csv') as fs:
    for line in fs:
        u,v,r,t = map(int,line.strip().split(','))
        if u not in nodes:
            node_map[u] = node_id 
            node_id+=1
            nodes.append(u)
        if v not in nodes:
            node_map[v] = node_id 
            node_id+=1
            nodes.append(v)
        G.add_edge(node_map[u],node_map[v])

In [4]:
len(nodes)

3783

In [5]:
#obtain normalized numpy matrix
normLap = torch.from_numpy(nx.normalized_laplacian_matrix(G).toarray())

In [6]:
normLap.shape

torch.Size([3783, 3783])

In [7]:
normLap[0]

tensor([ 1.0000, -0.0442,  0.0000,  ...,  0.0000,  0.0000,  0.0000], dtype=torch.float64)

In [8]:
for x in G.neighbors(0):
    print(x)

1


In [ ]:
class ModelStatic(nn.Module):
    def __init__(self,input_size,layers,hidden_size,output_size,graph,features):
        super(ModelStatic,self).__init__()
        W = nn.Parameter(torch.rand(input_size,hidden_size))
        
        
    def forward(self,in)    
        

In [9]:
C_1 = torch.randint(10,(3,3))

In [10]:
C_2 = torch.ones(3,3)

In [11]:
C_1

tensor([[ 1.,  9.,  4.],
        [ 3.,  3.,  0.],
        [ 0.,  9.,  9.]])

In [12]:
C_2

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [13]:
C_1[0] = C_2[0]

In [14]:
C_1

tensor([[ 1.,  1.,  1.],
        [ 3.,  3.,  0.],
        [ 0.,  9.,  9.]])

In [15]:
C_2

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [16]:
C_2[1] = C_1[1]

In [17]:
C_2

tensor([[ 1.,  1.,  1.],
        [ 3.,  3.,  0.],
        [ 1.,  1.,  1.]])

In [18]:
C_1

tensor([[ 1.,  1.,  1.],
        [ 3.,  3.,  0.],
        [ 0.,  9.,  9.]])

In [19]:
C_1 = C_2

In [20]:
C_1

tensor([[ 1.,  1.,  1.],
        [ 3.,  3.,  0.],
        [ 1.,  1.,  1.]])

In [21]:
C_2

tensor([[ 1.,  1.,  1.],
        [ 3.,  3.,  0.],
        [ 1.,  1.,  1.]])

In [44]:
W = torch.t(torch.randint(10,(3,4)))

In [42]:
V = torch.FloatTensor([1,2,3]).view(-1,1)

In [38]:
W.shape

torch.Size([3, 4])

In [39]:
V.shape

torch.Size([1, 3])

In [45]:
torch.matmul(W,V)

tensor([[ 45.],
        [ 20.],
        [ 28.],
        [ 19.]])

In [48]:
W_k = torch.randint(10,(5,4,3))

In [50]:
out = torch.matmul(W_k,V)

In [51]:
out.shape

torch.Size([5, 4, 1])

In [52]:
V = torch.FloatTensor([[1,2,3],[2,1,2],[3,2,1]])

In [53]:
V.shape

torch.Size([3, 3])

In [56]:
out_1 = torch.matmul(W_k,V)

In [57]:
out_1.shape

torch.Size([5, 4, 3])

In [65]:
out_1

tensor([[[ 32.,  27.,  28.],
         [ 17.,  18.,  19.],
         [ 19.,  14.,   9.],
         [ 28.,  21.,  16.]],

        [[ 28.,  20.,  28.],
         [ 18.,  23.,  34.],
         [ 36.,  29.,  32.],
         [ 34.,  21.,  18.]],

        [[ 42.,  35.,  42.],
         [ 20.,  15.,  24.],
         [ 33.,  23.,  31.],
         [ 31.,  29.,  41.]],

        [[ 35.,  25.,  29.],
         [ 16.,  12.,  16.],
         [ 19.,  20.,  33.],
         [ 29.,  18.,  23.]],

        [[ 34.,  32.,  30.],
         [ 16.,  18.,  24.],
         [ 34.,  29.,  42.],
         [ 25.,  27.,  39.]]])

In [66]:
X_1 = torch.unbind(out_1,dim=0)

In [72]:
for Y in X_1:
    print(Y.t())
    break

tensor([[ 32.,  17.,  19.,  28.],
        [ 27.,  18.,  14.,  21.],
        [ 28.,  19.,   9.,  16.]])


In [73]:
normLap[0]

tensor([ 1.0000, -0.0442,  0.0000,  ...,  0.0000,  0.0000,  0.0000], dtype=torch.float64)

In [74]:
normLap.shape

torch.Size([3783, 3783])

In [77]:
W = nn.Parameter(torch.rand(10,100,3783,dtype=torch.float64))

In [85]:
C_old = torch.matmul(W,normLap)

In [86]:
Y = torch.unbind(C_old,dim=0)

In [87]:
C_old.shape

torch.Size([10, 100, 3783])

In [88]:
C_new = torch.zeros(10,100,3783,dtype=torch.float64)